/*
 * eHelply SDK - 1.1.122
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateNoteResponse {
    #[serde(rename = "uuid")]
    pub uuid: String,
}

impl CreateNoteResponse {
    pub fn new(uuid: String) -> CreateNoteResponse {
        CreateNoteResponse {
            uuid,
        }
    }
}


