/*
 * eHelply SDK - 1.1.118
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.118
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */

/// DatesMeta : Date based meta



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DatesMeta {
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl DatesMeta {
    /// Date based meta
    pub fn new() -> DatesMeta {
        DatesMeta {
            created_at: None,
            updated_at: None,
        }
    }
}


