/*
 * eHelply SDK - 1.1.121
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.121
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MetaCustom {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "list", skip_serializing_if = "Option::is_none")]
    pub list: Option<Vec<crate::models::CustomList>>,
}

impl MetaCustom {
    pub fn new() -> MetaCustom {
        MetaCustom {
            name: None,
            description: None,
            list: None,
        }
    }
}


