/*
 * eHelply SDK - 1.1.107
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.107
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectsUsageTypeUnitPrice {
    #[serde(rename = "min_quantity")]
    pub min_quantity: i32,
    #[serde(rename = "max_quantity")]
    pub max_quantity: i32,
    #[serde(rename = "unit_price")]
    pub unit_price: i32,
}

impl ProjectsUsageTypeUnitPrice {
    pub fn new(min_quantity: i32, max_quantity: i32, unit_price: i32) -> ProjectsUsageTypeUnitPrice {
        ProjectsUsageTypeUnitPrice {
            min_quantity,
            max_quantity,
            unit_price,
        }
    }
}


