/*
 * eHelply SDK - 1.1.122
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */

/// SecurityKeyCreate : Used for create endpoint



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SecurityKeyCreate {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "summary")]
    pub summary: String,
}

impl SecurityKeyCreate {
    /// Used for create endpoint
    pub fn new(name: String, summary: String) -> SecurityKeyCreate {
        SecurityKeyCreate {
            name,
            summary,
        }
    }
}


