/*
 * eHelply SDK - 1.1.122
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceSuperStackMetaGettingStartedEndpointTeaser {
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "method")]
    pub method: String,
    #[serde(rename = "description")]
    pub description: String,
}

impl ServiceSuperStackMetaGettingStartedEndpointTeaser {
    pub fn new(path: String, method: String, description: String) -> ServiceSuperStackMetaGettingStartedEndpointTeaser {
        ServiceSuperStackMetaGettingStartedEndpointTeaser {
            path,
            method,
            description,
        }
    }
}


