/*
 * eHelply SDK - 1.1.122
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceSuperStackMetaFaq {
    #[serde(rename = "question")]
    pub question: String,
    #[serde(rename = "answer")]
    pub answer: String,
}

impl ServiceSuperStackMetaFaq {
    pub fn new(question: String, answer: String) -> ServiceSuperStackMetaFaq {
        ServiceSuperStackMetaFaq {
            question,
            answer,
        }
    }
}


