/*
 * eHelply SDK - 1.1.120
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.120
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ServiceSuperStackMetaFeature {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "summary")]
    pub summary: String,
}

impl ServiceSuperStackMetaFeature {
    pub fn new(name: String, summary: String) -> ServiceSuperStackMetaFeature {
        ServiceSuperStackMetaFeature {
            name,
            summary,
        }
    }
}


