/*
 * eHelply SDK - 1.1.122
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.122
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StaffResponse {
    #[serde(rename = "entity_uuid")]
    pub entity_uuid: String,
    #[serde(rename = "project_uuid", skip_serializing_if = "Option::is_none")]
    pub project_uuid: Option<String>,
    #[serde(rename = "schedule_uuid", skip_serializing_if = "Option::is_none")]
    pub schedule_uuid: Option<String>,
    #[serde(rename = "catalog_uuid", skip_serializing_if = "Option::is_none")]
    pub catalog_uuid: Option<String>,
    #[serde(rename = "review_group_uuid", skip_serializing_if = "Option::is_none")]
    pub review_group_uuid: Option<String>,
    #[serde(rename = "uuid")]
    pub uuid: String,
    #[serde(rename = "entity", skip_serializing_if = "Option::is_none")]
    pub entity: Option<String>,
    #[serde(rename = "place", skip_serializing_if = "Option::is_none")]
    pub place: Option<serde_json::Value>,
    #[serde(rename = "place_roles", skip_serializing_if = "Option::is_none")]
    pub place_roles: Option<Vec<String>>,
    #[serde(rename = "company", skip_serializing_if = "Option::is_none")]
    pub company: Option<serde_json::Value>,
    #[serde(rename = "company_roles", skip_serializing_if = "Option::is_none")]
    pub company_roles: Option<Vec<String>>,
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<serde_json::Value>,
    #[serde(rename = "catalog", skip_serializing_if = "Option::is_none")]
    pub catalog: Option<serde_json::Value>,
    #[serde(rename = "reviews", skip_serializing_if = "Option::is_none")]
    pub reviews: Option<serde_json::Value>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
    #[serde(rename = "deleted_at", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<String>,
}

impl StaffResponse {
    pub fn new(entity_uuid: String, uuid: String) -> StaffResponse {
        StaffResponse {
            entity_uuid,
            project_uuid: None,
            schedule_uuid: None,
            catalog_uuid: None,
            review_group_uuid: None,
            uuid,
            entity: None,
            place: None,
            place_roles: None,
            company: None,
            company_roles: None,
            schedule: None,
            catalog: None,
            reviews: None,
            created_at: None,
            updated_at: None,
            deleted_at: None,
        }
    }
}


