/*
 * eHelply SDK - 1.1.116
 *
 * eHelply SDK for SuperStack Services
 *
 * The version of the OpenAPI document: 1.1.116
 * Contact: support@ehelply.com
 * Generated by: https://openapi-generator.tech
 */

/// UserTokenReturn : Tokens, naming scheme based off of cognito return fields



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UserTokenReturn {
    #[serde(rename = "AccessToken")]
    pub access_token: String,
    #[serde(rename = "ExpiresIn")]
    pub expires_in: i32,
    #[serde(rename = "TokenType")]
    pub token_type: String,
    #[serde(rename = "IdToken")]
    pub id_token: String,
}

impl UserTokenReturn {
    /// Tokens, naming scheme based off of cognito return fields
    pub fn new(access_token: String, expires_in: i32, token_type: String, id_token: String) -> UserTokenReturn {
        UserTokenReturn {
            access_token,
            expires_in,
            token_type,
            id_token,
        }
    }
}


