name: Publish SDK
concurrency: sdk_publish
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v2
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Publish to Cargo
        run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATESIO_API_KEY }}

  notifications:
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Slack Failure Notification
        if: needs.build.result == 'failure'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: '#9e101e'
          SLACK_USERNAME: 'GitHub SDK Bot'
          SLACK_ICON: "https://assets.ehelply.com/logo/ehelply/base/symbol_green_white.png"
          SLACK_FOOTER: ""
          SLACK_TITLE: 'Rust SDK Publish FAILED'
          SLACK_MESSAGE: 'Failed to publish the Rust SDK to Crates.io'
      - name: Slack Success Notification
        if: always() && needs.build.result == 'success'
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: 'good'
          SLACK_USERNAME: 'GitHub SDK Bot'
          SLACK_ICON: "https://assets.ehelply.com/logo/ehelply/base/symbol_green_white.png"
          SLACK_FOOTER: ""
          SLACK_TITLE: 'Rust SDK Publish SUCCESS'
          SLACK_MESSAGE: 'Rust SDK pushed to Crates.io successfully'